# Generated by Django 3.1.14 on 2021-12-18 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='type',
            field=models.IntegerField(choices=[(1, 'Page'), (2, 'Category'), (3, 'Ringtone')], default=1, verbose_name='Page type'),
        ),
    ]
