# Generated by Django 3.1.5 on 2021-06-13 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PageIds',
        ),
    ]
