# Generated by Django 3.1.14 on 2021-12-18 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_auto_20210712_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactusplugin',
            name='tagline',
            field=models.CharField(help_text='Tagline of contact us.', max_length=1000, verbose_name='Tagline'),
        ),
        migrations.AlterField(
            model_name='footerplugin',
            name='copyright',
            field=models.CharField(help_text='Copyright line of footer.', max_length=1000, verbose_name='Copyright line'),
        ),
    ]
