# Generated by Django 3.1.14 on 2021-12-19 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0005_auto_20211219_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoriteplugin',
            name='ringtone_type',
            field=models.IntegerField(choices=[(1, 'New'), (2, 'Popular'), (3, 'Top50')], default=1, verbose_name='Ringtone type of container'),
        ),
    ]
